server:
  port: 83

spring:
  redis:
    host: 39.104.69.80
    port: 8097
    ssl: false
    database: 0
    # Redis服务器连接密码（默认为空）
    #password:
    # 连接池最大连接数（使用负值表示没有限制）
    # 连接超时时间（毫秒）
    timeout: 60000

  thymeleaf:
    cache:
      false


